In [1]:
import torch
import numpy as np

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

x*y

tensor([10.,  3.])

In [3]:
x = torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])
y

tensor([[0.1313, 0.0651, 0.1630, 0.6399, 0.4541],
        [0.0951, 0.1993, 0.1481, 0.0895, 0.8271]])

In [6]:
# Reshape is called view, for example to flatten
y.view([1, 10])

tensor([[0.1313, 0.0651, 0.1630, 0.6399, 0.4541, 0.0951, 0.1993, 0.1481, 0.0895,
         0.8271]])

In [7]:
y.view([5,2])

tensor([[0.1313, 0.0651],
        [0.1630, 0.6399],
        [0.4541, 0.0951],
        [0.1993, 0.1481],
        [0.0895, 0.8271]])

In [8]:
# broadcasting errors?
y.view([3,3])
# yes

RuntimeError: shape '[3, 3]' is invalid for input of size 10

In [9]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [10]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5823, 0.5980],
        [0.2892, 0.3317]]) 



In [12]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])  # or [:, -1]
tensor[:,1] = 0   # mutable
tensor

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
if torch.cuda.is_available():  # takes a second
    print('cuda time')
    tensor = tensor.to('cuda')

cuda time


In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)  # concatenate
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')

In [15]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
t2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

In [16]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [17]:
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [18]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [19]:
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)  # out gives the output tensor, not necessary

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [20]:
tensor.sum()

tensor(12., device='cuda:0')

In [21]:
tensor.sum().item()  # gives a float

12.0

In [22]:
tensor.add_(5)  # inplace operation, not liking it
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]], device='cuda:0')

In [23]:
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [24]:
tensor.cpu().numpy()  # much quicker than to cuda

array([[6., 5., 6., 6.],
       [6., 5., 6., 6.],
       [6., 5., 6., 6.],
       [6., 5., 6., 6.]], dtype=float32)

In [25]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [26]:
t.add_(1)  # inplace is working on both the tensor and the array, terrible
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [27]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
